import fs from "node:fs/promises";
import path from "node:path";

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../../..");
const commandsDir = path.join(repoRoot, "otto-command-service/commands");
const outFile = path.join(repoRoot, "src/generated_cli/index.ts");

const files = (await fs.readdir(commandsDir)).filter((f) => f.endsWith(".json")).sort();
const schemas = [];
for (const file of files) {
  const raw = await fs.readFile(path.join(commandsDir, file), "utf8");
  schemas.push(JSON.parse(raw));
}

const commandNames = schemas.map((s) => s.name);

const emitted = `/* eslint-disable */\n` +
`// Auto-generated by otto-command-service/generators/cli-generator\n\n` +
`import { executeGeneratedCommand } from \"../generated_api/index.js\";\n\n` +
`export type GeneratedCliCommandName = ${commandNames.map((name) => `\"${name}\"`).join(" | ")};\n\n` +
`export const generatedCliCommands: GeneratedCliCommandName[] = ${JSON.stringify(commandNames, null, 2)} as GeneratedCliCommandName[];\n\n` +
`export async function runGeneratedCliCommand(commandName: GeneratedCliCommandName, params: Record<string, unknown> = {}): Promise<unknown> {\n` +
`  return executeGeneratedCommand(commandName, params);\n` +
`}\n`;

await fs.mkdir(path.dirname(outFile), { recursive: true });
await fs.writeFile(outFile, emitted, "utf8");
console.log(`generated ${outFile}`);
