/* eslint-disable */
// Auto-generated by otto-command-service/generators/api-generator

export type GeneratedCommandSchema = {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
  returnType: Record<string, unknown>;
  errorTypes: string[];
  permissions: string[];
  routing: {
    handlerModule: string;
    handlerExport: string;
    exposedAs: string[];
    http: { method: string; path: string };
  };
};

export const generatedCommandSchemas: GeneratedCommandSchema[] = [
  {
    "name": "config.set",
    "description": "Mutate OttoUpdate server configuration.",
    "parameters": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "default": "./config/server.toml"
        },
        "bind": {
          "type": [
            "string",
            "null"
          ]
        },
        "bearer_token": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "returnType": {
      "type": "object",
      "properties": {
        "updatedPath": {
          "type": "string"
        },
        "bind": {
          "type": "string"
        },
        "bearer_token": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "errorTypes": [
      "ConfigWriteError",
      "ConfigParseError"
    ],
    "permissions": [
      "config:write"
    ],
    "routing": {
      "handlerModule": "configSet.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/config/set"
      }
    }
  },
  {
    "name": "config.show",
    "description": "Display OttoUpdate server configuration.",
    "parameters": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "default": "./config/server.toml"
        }
      }
    },
    "returnType": {
      "type": "object",
      "properties": {
        "bind": {
          "type": "string"
        },
        "bearer_token": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "errorTypes": [
      "ConfigReadError",
      "ConfigParseError"
    ],
    "permissions": [
      "config:read"
    ],
    "routing": {
      "handlerModule": "configShow.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "GET",
        "path": "/v1/commands/config/show"
      }
    }
  },
  {
    "name": "service.install",
    "description": "Install OttoUpdate service.",
    "parameters": {
      "type": "object",
      "properties": {}
    },
    "returnType": {
      "type": "object",
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "errorTypes": [
      "UnsupportedPlatformError",
      "ServiceCommandError"
    ],
    "permissions": [
      "service:manage"
    ],
    "routing": {
      "handlerModule": "serviceInstall.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/service/install"
      }
    }
  },
  {
    "name": "service.start",
    "description": "Start OttoUpdate service.",
    "parameters": {
      "type": "object",
      "properties": {}
    },
    "returnType": {
      "type": "object",
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "errorTypes": [
      "UnsupportedPlatformError",
      "ServiceCommandError"
    ],
    "permissions": [
      "service:manage"
    ],
    "routing": {
      "handlerModule": "serviceStart.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/service/start"
      }
    }
  },
  {
    "name": "service.status",
    "description": "Query OttoUpdate service status.",
    "parameters": {
      "type": "object",
      "properties": {}
    },
    "returnType": {
      "type": "object",
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "errorTypes": [
      "UnsupportedPlatformError",
      "ServiceCommandError"
    ],
    "permissions": [
      "service:read"
    ],
    "routing": {
      "handlerModule": "serviceStatus.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "GET",
        "path": "/v1/commands/service/status"
      }
    }
  },
  {
    "name": "service.stop",
    "description": "Stop OttoUpdate service.",
    "parameters": {
      "type": "object",
      "properties": {}
    },
    "returnType": {
      "type": "object",
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "errorTypes": [
      "UnsupportedPlatformError",
      "ServiceCommandError"
    ],
    "permissions": [
      "service:manage"
    ],
    "routing": {
      "handlerModule": "serviceStop.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/service/stop"
      }
    }
  },
  {
    "name": "service.uninstall",
    "description": "Uninstall OttoUpdate service.",
    "parameters": {
      "type": "object",
      "properties": {}
    },
    "returnType": {
      "type": "object",
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "errorTypes": [
      "UnsupportedPlatformError",
      "ServiceCommandError"
    ],
    "permissions": [
      "service:manage"
    ],
    "routing": {
      "handlerModule": "serviceUninstall.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "DELETE",
        "path": "/v1/commands/service/uninstall"
      }
    }
  }
] as GeneratedCommandSchema[];

export async function executeGeneratedCommand(commandName: string, params: Record<string, unknown> = {}): Promise<unknown> {
  const schema = generatedCommandSchemas.find((entry) => entry.name === commandName);
  if (!schema) {
    throw new Error(`Unknown generated command: ${commandName}`);
  }
  const handlerUrl = new URL(`../../otto-command-service/handlers/${schema.routing.handlerModule}`, import.meta.url);
  const mod = await import(handlerUrl.href);
  const fn = mod[schema.routing.handlerExport];
  if (typeof fn !== "function") {
    throw new Error(`Handler export not found for command ${commandName}: ${schema.routing.handlerExport}`);
  }
  return fn(params);
}
