/* eslint-disable */
// Auto-generated by otto-command-service/src/generators/api-generator

export type GeneratedCommandSchema = {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
  returnType: Record<string, unknown>;
  errorTypes: string[];
  permissions: string[];
  routing: Record<string, unknown> & {
    handlerModule: string;
    handlerExport: string;
    exposedAs: string[];
    http: { method: string; path: string };
  };
};

export const generatedCommandSchemas: GeneratedCommandSchema[] = [
  {
    "name": "config.set",
    "description": "Mutate OttoUpdate server configuration.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": false,
      "properties": {
        "path": {
          "type": "string",
          "default": "./config/server.toml"
        },
        "bind": {
          "type": [
            "string",
            "null"
          ]
        },
        "bearer_token": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "returnType": {
      "type": "object",
      "required": [
        "updatedPath",
        "bind",
        "bearer_token"
      ],
      "additionalProperties": false,
      "properties": {
        "updatedPath": {
          "type": "string"
        },
        "bind": {
          "type": "string"
        },
        "bearer_token": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "errorTypes": [
      "ConfigWriteError",
      "ConfigParseError"
    ],
    "permissions": [
      "config:write"
    ],
    "routing": {
      "handlerModule": "configSet.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/config/set"
      },
      "cli": {
        "group": "config",
        "command": "set"
      },
      "operationId": "configSet"
    }
  },
  {
    "name": "config.show",
    "description": "Display OttoUpdate server configuration.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": false,
      "properties": {
        "path": {
          "type": "string",
          "default": "./config/server.toml"
        }
      }
    },
    "returnType": {
      "type": "object",
      "required": [
        "bind",
        "bearer_token"
      ],
      "additionalProperties": false,
      "properties": {
        "bind": {
          "type": "string"
        },
        "bearer_token": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "errorTypes": [
      "ConfigReadError",
      "ConfigParseError"
    ],
    "permissions": [
      "config:read"
    ],
    "routing": {
      "handlerModule": "configShow.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "GET",
        "path": "/v1/commands/config/show"
      },
      "cli": {
        "group": "config",
        "command": "show"
      },
      "operationId": "configShow"
    }
  },
  {
    "name": "maestro.install",
    "description": "Install Maestro runtime via Otto lifecycle hooks.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": true,
      "properties": {
        "payloadPath": {
          "type": "string"
        },
        "channel": {
          "type": "string",
          "default": "stable"
        },
        "dryRun": {
          "type": "boolean",
          "default": false
        }
      }
    },
    "returnType": {
      "type": "object",
      "additionalProperties": true
    },
    "errorTypes": [
      "MaestroInstallError"
    ],
    "permissions": [
      "maestro:install"
    ],
    "routing": {
      "handlerModule": "maestroInstall.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/maestro/install"
      },
      "cli": {
        "group": "maestro",
        "command": "install"
      },
      "operationId": "maestroInstall"
    }
  },
  {
    "name": "maestro.repair",
    "description": "Repair Maestro runtime by replaying install lifecycle validation.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": true,
      "properties": {
        "verifyOnly": {
          "type": "boolean",
          "default": false
        },
        "dryRun": {
          "type": "boolean",
          "default": false
        }
      }
    },
    "returnType": {
      "type": "object",
      "additionalProperties": true
    },
    "errorTypes": [
      "MaestroRepairError"
    ],
    "permissions": [
      "maestro:repair"
    ],
    "routing": {
      "handlerModule": "maestroRepair.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/maestro/repair"
      },
      "cli": {
        "group": "maestro",
        "command": "repair"
      },
      "operationId": "maestroRepair"
    }
  },
  {
    "name": "maestro.uninstall",
    "description": "Uninstall Maestro runtime by invoking pre-uninstall lifecycle hook.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": true,
      "properties": {
        "purgeData": {
          "type": "boolean",
          "default": false
        },
        "dryRun": {
          "type": "boolean",
          "default": false
        }
      }
    },
    "returnType": {
      "type": "object",
      "additionalProperties": true
    },
    "errorTypes": [
      "MaestroUninstallError"
    ],
    "permissions": [
      "maestro:uninstall"
    ],
    "routing": {
      "handlerModule": "maestroUninstall.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "DELETE",
        "path": "/v1/commands/maestro/uninstall"
      },
      "cli": {
        "group": "maestro",
        "command": "uninstall"
      },
      "operationId": "maestroUninstall"
    }
  },
  {
    "name": "maestro.update",
    "description": "Update Maestro runtime via Otto lifecycle hooks.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": true,
      "properties": {
        "channel": {
          "type": "string",
          "default": "stable"
        },
        "dryRun": {
          "type": "boolean",
          "default": false
        }
      }
    },
    "returnType": {
      "type": "object",
      "additionalProperties": true
    },
    "errorTypes": [
      "MaestroUpdateError"
    ],
    "permissions": [
      "maestro:update"
    ],
    "routing": {
      "handlerModule": "maestroUpdate.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/maestro/update"
      },
      "cli": {
        "group": "maestro",
        "command": "update"
      },
      "operationId": "maestroUpdate"
    }
  },
  {
    "name": "service.install",
    "description": "Install OttoUpdate service.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": false,
      "properties": {}
    },
    "returnType": {
      "type": "object",
      "required": [
        "ok",
        "message"
      ],
      "additionalProperties": false,
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "errorTypes": [
      "UnsupportedPlatformError",
      "ServiceCommandError"
    ],
    "permissions": [
      "service:manage"
    ],
    "routing": {
      "handlerModule": "serviceInstall.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/service/install"
      },
      "cli": {
        "group": "service",
        "command": "install"
      },
      "operationId": "serviceInstall"
    }
  },
  {
    "name": "service.start",
    "description": "Start OttoUpdate service.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": false,
      "properties": {}
    },
    "returnType": {
      "type": "object",
      "required": [
        "ok",
        "message"
      ],
      "additionalProperties": false,
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "errorTypes": [
      "UnsupportedPlatformError",
      "ServiceCommandError"
    ],
    "permissions": [
      "service:manage"
    ],
    "routing": {
      "handlerModule": "serviceStart.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/service/start"
      },
      "cli": {
        "group": "service",
        "command": "start"
      },
      "operationId": "serviceStart"
    }
  },
  {
    "name": "service.status",
    "description": "Query OttoUpdate service status.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": false,
      "properties": {}
    },
    "returnType": {
      "type": "object",
      "required": [
        "ok",
        "message"
      ],
      "additionalProperties": false,
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "errorTypes": [
      "UnsupportedPlatformError",
      "ServiceCommandError"
    ],
    "permissions": [
      "service:read"
    ],
    "routing": {
      "handlerModule": "serviceStatus.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "GET",
        "path": "/v1/commands/service/status"
      },
      "cli": {
        "group": "service",
        "command": "status"
      },
      "operationId": "serviceStatus"
    }
  },
  {
    "name": "service.stop",
    "description": "Stop OttoUpdate service.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": false,
      "properties": {}
    },
    "returnType": {
      "type": "object",
      "required": [
        "ok",
        "message"
      ],
      "additionalProperties": false,
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "errorTypes": [
      "UnsupportedPlatformError",
      "ServiceCommandError"
    ],
    "permissions": [
      "service:manage"
    ],
    "routing": {
      "handlerModule": "serviceStop.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "POST",
        "path": "/v1/commands/service/stop"
      },
      "cli": {
        "group": "service",
        "command": "stop"
      },
      "operationId": "serviceStop"
    }
  },
  {
    "name": "service.uninstall",
    "description": "Uninstall OttoUpdate service.",
    "parameters": {
      "type": "object",
      "required": [],
      "additionalProperties": false,
      "properties": {}
    },
    "returnType": {
      "type": "object",
      "required": [
        "ok",
        "message"
      ],
      "additionalProperties": false,
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "errorTypes": [
      "UnsupportedPlatformError",
      "ServiceCommandError"
    ],
    "permissions": [
      "service:manage"
    ],
    "routing": {
      "handlerModule": "serviceUninstall.mjs",
      "handlerExport": "handle",
      "exposedAs": [
        "cli",
        "api"
      ],
      "http": {
        "method": "DELETE",
        "path": "/v1/commands/service/uninstall"
      },
      "cli": {
        "group": "service",
        "command": "uninstall"
      },
      "operationId": "serviceUninstall"
    }
  }
] as GeneratedCommandSchema[];

export async function executeGeneratedCommand(commandName: string, params: Record<string, unknown> = {}): Promise<unknown> {
  const schema = generatedCommandSchemas.find((entry) => entry.name === commandName);
  if (!schema) {
    throw new Error(`Unknown generated command: ${commandName}`);
  }
  const handlerUrl = new URL(`../../otto-command-service/src/handlers/${schema.routing.handlerModule}`, import.meta.url);
  const mod = await import(handlerUrl.href);
  const fn = mod[schema.routing.handlerExport];
  if (typeof fn !== "function") {
    throw new Error(`Handler export not found for command ${commandName}: ${schema.routing.handlerExport}`);
  }
  return fn(params);
}
