/* eslint-disable */
// Auto-generated by otto-command-service/generators/cli-generator

import { executeGeneratedCommand } from "../generated_api/index.js";

export type GeneratedCliCommandName = "config.set" | "config.show" | "service.install" | "service.start" | "service.status" | "service.stop" | "service.uninstall";

export const generatedCliCommands: GeneratedCliCommandName[] = [
  "config.set",
  "config.show",
  "service.install",
  "service.start",
  "service.status",
  "service.stop",
  "service.uninstall"
] as GeneratedCliCommandName[];

export async function runGeneratedCliCommand(commandName: GeneratedCliCommandName, params: Record<string, unknown> = {}): Promise<unknown> {
  return executeGeneratedCommand(commandName, params);
}
