import fs from "node:fs/promises";
import path from "node:path";

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../../..");
const commandsDir = path.join(repoRoot, "otto-command-service/commands");
const outFile = path.join(repoRoot, "src/generated_api/index.ts");

const files = (await fs.readdir(commandsDir)).filter((f) => f.endsWith(".json")).sort();
const schemas = [];

for (const file of files) {
  const raw = await fs.readFile(path.join(commandsDir, file), "utf8");
  schemas.push(JSON.parse(raw));
}

const emitted = `/* eslint-disable */\n` +
`// Auto-generated by otto-command-service/generators/api-generator\n\n` +
`export type GeneratedCommandSchema = {\n` +
`  name: string;\n` +
`  description: string;\n` +
`  parameters: Record<string, unknown>;\n` +
`  returnType: Record<string, unknown>;\n` +
`  errorTypes: string[];\n` +
`  permissions: string[];\n` +
`  routing: {\n` +
`    handlerModule: string;\n` +
`    handlerExport: string;\n` +
`    exposedAs: string[];\n` +
`    http: { method: string; path: string };\n` +
`  };\n` +
`};\n\n` +
`export const generatedCommandSchemas: GeneratedCommandSchema[] = ${JSON.stringify(schemas, null, 2)} as GeneratedCommandSchema[];\n\n` +
`export async function executeGeneratedCommand(commandName: string, params: Record<string, unknown> = {}): Promise<unknown> {\n` +
`  const schema = generatedCommandSchemas.find((entry) => entry.name === commandName);\n` +
`  if (!schema) {\n` +
`    throw new Error(\`Unknown generated command: \${commandName}\`);\n` +
`  }\n` +
`  const handlerUrl = new URL(\`../../otto-command-service/handlers/\${schema.routing.handlerModule}\`, import.meta.url);\n` +
`  const mod = await import(handlerUrl.href);\n` +
`  const fn = mod[schema.routing.handlerExport];\n` +
`  if (typeof fn !== \"function\") {\n` +
`    throw new Error(\`Handler export not found for command \${commandName}: \${schema.routing.handlerExport}\`);\n` +
`  }\n` +
`  return fn(params);\n` +
`}\n`;

await fs.mkdir(path.dirname(outFile), { recursive: true });
await fs.writeFile(outFile, emitted, "utf8");
console.log(`generated ${outFile}`);
